### ISSUE TITLE
Error exporting assets for (new?) maps

### ISSUE THREAD

**Issue by RutoKZ** [Metapyziks/SourceUtils#19]
Error exporting (new?) maps, particularly kz_11735,kz_atectasis,kz_cdr_myst,kz_cdr_mysterious,kz_cdr_slash,kz_comboya,kz_morestairs,kz_oloramasa,kz_quadrant_fix,kz_smallmap,kz_yoink

`<!DOCTYPE html>
<html>
  <head>
    <title>500: InternalServerError</title>
  </head>
  <body>
    <h2>500: InternalServerError</h2>
    Request:&nbsp;<code>http://localhost:39281/maps/kz_yoink/index.json</code>
    <br />
    Message:&nbsp;<code>Static prop version 11 is not supported.</code>
    <br />
    <code style="padding:8px;white-space:pre-wrap;display:block;">
Ziks.WebServer.ControllerActionException: Static prop version 11 is not supported. ---&gt; System.NotSupportedException: Static prop version 11 is not supported.
   at SourceUtils.ValveBsp.StaticProps.EnsureLoaded() in C:\Users\James\Documents\GitHub\SourceUtils\SourceUtils\ValveBsp\StaticProps.cs:line 283
   at SourceUtils.ValveBsp.StaticProps.get_PropCount() in C:\Users\James\Documents\GitHub\SourceUtils\SourceUtils\ValveBsp\StaticProps.cs:line 178
   at SourceUtils.WebExport.Bsp.IndexController.GetIndexJson(String map)
   at lambda_method(Closure , Controller )
   at Ziks.WebServer.ControllerActionMap.TryInvokeAction(Controller controller, HttpListenerRequest request)
   at Ziks.WebServer.Controller.Service(HttpListenerContext context, Session session)
   --- End of inner exception stack trace ---
    </code>
  </body>
</html>`

**Comment by Metapyziks** [comment]
Thank you for reporting, I should be able to look into this today or tomorrow.

**Comment by Metapyziks** [comment]
Can reproduce on recently recompiled Valve maps too.

**Comment by Metapyziks** [comment]
Fixed in 60a453629a2caea479660398fb94a21a937523ef

**Comment by RutoKZ** [comment]
All the maps above mentioned now exports correctly except for kz_11735, giving this error
<!DOCTYPE html>
<html>
  <head>
    <title>500: InternalServerError</title>
  </head>
  <body>
    <h2>500: InternalServerError</h2>
    Request:&nbsp;<code>http://localhost:39281/maps/kz_11735/materials/matpage0.json
      </code>
    <br />
    Message:&nbsp;<code>VTF format: I8</code>
    <br />
    <code style="padding:8px;white-space:pre-wrap;display:block;">
Ziks.WebServer.ControllerActionException: VTF format: I8 ---&gt; System.NotImplementedException: VTF format: I8
   at SourceUtils.ValveTextureFile..ctor(Stream stream, Boolean onlyHeader)
   at SourceUtils.WebExport.Texture.Get(ValveBspFile bsp, String path)
   at SourceUtils.WebExport.Bsp.MaterialController.GetPage(String map, Int32 index)
   at lambda_method(Closure , Controller )
   at Ziks.WebServer.ControllerActionMap.TryInvokeAction(Controller controller, HttpListenerRequest request)
   at Ziks.WebServer.Controller.Service(HttpListenerContext context, Session session)
   --- End of inner exception stack trace ---
    </code>
  </body>
</html>
